# Generated by Django 5.2.13 on 2026-04-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='api_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
