# Generated by Django 5.2.13 on 2026-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_alter_website_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
