# Generated by Django 5.2.13 on 2026-04-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_alter_website_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='required_fields',
            field=models.JSONField(blank=True, default=list, help_text='Fields to collect before connecting to agent e.g. ["name", "email", "phone", "issue"]'),
        ),
    ]
