# Generated by Django 5.2.13 on 2026-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('text', 'Text Paste')], default='file', help_text='Whether document was uploaded as file or pasted text', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='text_content',
            field=models.TextField(blank=True, help_text='Raw text content for text-paste uploads', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
