# Generated by Django 5.2.13 on 2026-04-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_document_doc_type_document_text_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('text', 'Text Paste')], default='file', help_text='Whether document was uploaded as file or pasted text', max_length=20),
        ),
    ]
