# Generated by Django 5.2.13 on 2026-04-18 12:32

import django.db.models.deletion
import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_alter_document_file_type'),
        ('websites', '0003_alter_website_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='knowledge_base_document',
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.document')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='websites.website')),
            ],
            options={
                'db_table': 'knowledge_base_documentchunk',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['website', 'document'], name='knowledge_b_website_f1f601_idx'), models.Index(fields=['website'], name='knowledge_b_website_c39843_idx')],
            },
        ),
    ]
