# Generated by Django 5.2.12 on 2026-04-01 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCallback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callback_requests', to='chat.chatsession')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_requests', to='websites.website')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
