# Generated by Django 5.2.12 on 2026-04-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_requestcallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcallback',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='requestcallback',
            name='subject',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Technical Support'), ('billing', 'Billing & Payments'), ('sales', 'Sales & Pricing'), ('complaint', 'Complaint'), ('other', 'Other')], default='general', max_length=50),
        ),
    ]
