# Generated by Django 5.2.13 on 2026-04-24 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_requestcallback_email_requestcallback_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_live_agent_active',
            field=models.BooleanField(default=False),
        ),
    ]
