# Generated by Django 5.2.13 on 2026-04-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatsession_is_live_agent_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='visitor_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
