# Generated by Django 5.2.13 on 2026-04-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatsession_visitor_details'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'timestamp'], name='message_session_timestamp_idx'),
        ),
    ]
