# Generated by Django 5.2.13 on 2026-04-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_message_session_timestamp_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('agent', 'Agent'), ('system', 'System')], max_length=20),
        ),
    ]
